### ISSUE TITLE
function arguments not available in the interactive (debug) console

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#119]
``` yml
entities: 
    person: 
        processes: 
            func:
                args: arg
                code: 
                    - localarg: arg
                    # function arguments are not available in the interactive
                    # console, but local variables work fine:
                    # >>> arg
                    # name 'arg' is not defined
                    # >>> localarg
                    #1.0
                    - breakpoint()

            test_call:
                - func(1.0)

simulation:
    processes:    
        - person: [test_call]

    input:
        file: simple2001.h5
    output:
        file: simulation.h5

    start_period: 2002
    periods: 1
```
