### ISSUE TITLE
question: group processes with different entities

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#201]
Imagine I have something similar in my `console.yml  file:
```yaml
processes:
    - individus: [naissance]
    - generations: [mise_a_jour]
    - individus: [mise_a_jour]
```
Is there a way to group the last two processes to have something looking like this: 
```yaml

mise_a_jour: {generation: mise_a_jour, individus: mise_a_jour}

processes:
    - individus: [naissance]
    - mise_a_jour
```

**Comment by gdementen** [comment]
Currently there is no way to do that. Honestly, in this example, I do not see the point. Is there an actual use case that would justify the feature better?

**Comment by benjello** [comment]
I am trying to build modular configuration. I need à skeleton of processes
that I can override. The only problem i have right now is when I want to
add a new entity to the standard configuration. I can't find a way to
exécuté its processes since it os not present in the standard version.

Le lun. 21 déc. 2015 20:41, Gaëtan de Menten <notifications@github.com> a
écrit :

> Currently there is no way to do that. Honestly, in this example, I do not
> see the point. Is there an actual use case that would justify the feature
> better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liam2/liam2/issues/201#issuecomment-166400035>.
>
-- 
Mahdi Ben Jelloul

**Comment by gdementen** [comment]
You know you can override the processes list when importing another model,
right? Yes it's cumbersome because you have to override the whole thing
(potentially to insert only a single function) but it *is* possible to
execute "new" entities processes.

On Mon, Dec 21, 2015 at 8:53 PM, Mahdi Ben Jelloul <notifications@github.com
> wrote:

> I am trying to build modular configuration. I need à skeleton of processes
> that I can override. The only problem i have right now is when I want to
> add a new entity to the standard configuration. I can't find a way to
> exécuté its processes since it os not present in the standard version.
>

**Comment by benjello** [comment]
I know I can code it on the python side but It is exactly what I wanted to avoid ;-)
I seek to keep the modularity on the liam side.

**Comment by gdementen** [comment]
I meant it in the LIAM2 side. See 
http://liam2.plan.be/documentation/0.11/import_model.html#import-models
(variant2.yml)

**Comment by benjello** [comment]
Yep: but you have to rewrite all the processes and you loose the modularity inside processes.

**Comment by gdementen** [comment]
One way to solve this would be to allow calling functions from other entities directly, so you could write:

```yaml
entities:
    individual:
        processes:
            update:
                ...
            update_all:
                - generation.update()
                - update()

processes:
    - individual: [birth, update_all]
```
This would be relatively easy to implement. The trick is that in `generation.update`, generation is the name of the entity, not the name of a possible link to "generation", which means modellers will need to have a different name for entities and the link that point to them, which is often not the case in current models. Calling functions over links would also be interesting to implement, but a bit harder.

**Comment by gdementen** [comment]
The above idea might be cleaner if we could have global processes.

```yaml
globals:
    data:
        periodic:
            path: param/globals.csv
            fields:
                # PERIOD is implicit
                - MINR: float
                - MIG_PERCENT: float

        ARRAY:
            type: float

        CHOICE2D:
            path: param/choice2d.csv
            type: float

    processes:
        update_all:
            - generation.update()
            - individual.update()

entities:
    individual:
        processes:
            update:
                ...

processes:
    - globals: [update_all]
```
OR
```yaml
globals:
    periodic:
        path: param/globals.csv
        fields:
            # PERIOD is implicit
            - MINR: float
            - MIG_PERCENT: float

    ARRAY:
        type: float

    CHOICE2D:
        path: param/choice2d.csv
        type: float

    processes:
        update_all:
            - generation.update()
            - individual.update()

entities:
    individual:
        processes:
            update:
                ...

processes:
    - globals: [update_all]
```
OR even
```yaml
globals:
    periodic:
        path: param/globals.csv
        fields:
            # PERIOD is implicit
            - MINR: float
            - MIG_PERCENT: float

    ARRAY:
        type: float

    CHOICE2D:
        path: param/choice2d.csv
        type: float

global_processes:
    update_all:
        - generation.update()
        - individual.update()

entities:
    individual:
        processes:
            update:
                ...

processes:
    - globals: [update_all]
