### ISSUE TITLE
add support for individual probabilities in choice

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#211]
```yaml
  current:
      test2:
          - threshold1: age / 200
          - threshold2: threshold1 + 0.1 + 0.3 * work
          - u: uniform()
          - event: if(u < threshold1, 1,
                       if(u < threshold2, 2,
                          3))
          - show(groupby(age, work, event))

  desired:
      test2:
          - prob1: age / 200
          - prob2: 0.1 + 0.3 * work
          # list of arrays
          - event: choice([1, 2, 3], [prob1, prob2, 1 - prob1 - prob2])
          # using a 2d array would make it easier in many cases (num_persons * num_choices)
          # e.g.
          # ARRAY is a 4d array, so the result is a 2d array  (num_persons * num_choices)
          - agegroup_idx: trunc(agegroup / 5)
          - event: choice([1, 2, 3], ARRAY[gender * 1, workstate, agegroup_idx])
          - show(groupby(age, work, event))
```
#117, would make this even nicer.
```yaml
  desired:
      test2:
          # using .points API as if we had LArray under the hood.
          - event: choice([1, 2, 3], ARRAY.points[gender, workstate, agegroup])
```

**Comment by gdementen** [comment]
#213 would make it yet nicer.
```yaml
  better:
      test2:
          - event_outcome: choice(EVENT_PROBABILITIES)
```
