### ISSUE TITLE
Use labels from LabeledArrays as choices

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#212]
This first requires #211.

``` yaml
  better:
      test2:
          # assume result of .points[] is a 2d LArray (num_persons, num_choices)
          # we use the labels from the array as the possible outcomes of the choice
          - event: choice(ARRAY.points[gender, workstate, agegroup])
```

The question is: which dimension do we take the labels from? The last by default, or the one named "choices"?
