### ISSUE TITLE
user-defined autoindex for globals

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#213]
Requires #117.

ie generalize periodic globals behavior (which automatically index the period) if we use the global name without indexing it. It wouldn't affect the behavior of indexed operation, so that we can still work on complete arrays by using GLOBAL[:].

The syntax would be something like:

``` yaml
globals:
    periodic:
        # this would still be the default for "periodic" but could be changed
        autoindex: period
        path: globals.csv
        fields: 
            - CPI: float

     INCOME:
         autoindex: gender, agegroup
         type: float 

    AL_FERTILITY:
        # Currently we do that implicitly in align(). In practice, it does not change 
        # the result but improves performance a lot (because the number of alignment
        # categories is much lower -- all categories for other periods would be empty 
        # anyway). 
        # Having it at this level would improve performance for what they do currently,
        # because currently, each period they compute stuff like 
        # ((AL_ACTIVE_POP - AL_UNEMPLOYED) / AL_POPULATION) * AL_WORKING_T_1,
        # which computes for all periods, then the alignment code discards all periods
        # except the current one.
        autoindex: period
        path: fertility.csv
        type: float
... 
entities:
    person:
        processes:
            compute_income:
                - income: MONTHLY_INCOME * months_worked
```

See also #26.

Question: do we want to generalize this further by applying it to entities/fields too? (this assumes fields are "viewed" as 2d arrays (periods, num_individuals), which is not the case currently but I always wished I could). 
A: I think that would be nice as it would make LIAM2 a lot more generic, but it is a long way before we can do this.
