### ISSUE TITLE
make choice take expressions from LArray labels

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#214]
To write nicer "choice" expressions, we could either implement #213, which is very powerful but possibly hard to implement (I don't think so), or we could do like align() and implement that behaviour in choice itself. Ie use dimension names as variables to be evaluated to subset the probabilities array.

``` yaml
  better:
      test2:
          - event_outcome: choice(EVENT_PROBABILITIES)
```
