### ISSUE TITLE
dump() duplicates all output: False fields

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#230]
e.g. modify demo01.yml
```yaml
entities:
    person:
        fields:
            - age:    {type: int, output: False}
            - gender: bool

        processes:
            ageing:
                - age: age + 1
                - show(dump(filter=id == 0))
```
results in:

```
period | id | age | gender | age
  2025 |  0 |  57 |   True |  57
```
