### ISSUE TITLE
dump() gets confused by variables created using array()

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#231]
```yaml
entities:
    person:
        processes:
            test:
                - new('person', number=5)
                - age: randint(100)
                - arr: array([age, age + 1])
                - show(dump())
                - show(dump(period, id, age))

simulation:
    processes:
        - person: [test]

    input:
        method: void
        file: none

    output:
        file: simulation.h5

    start_period: 2016
    periods: 1
```
will output something like:
```
period | id | age |              arr
  2016 |  0 |  38 | [38 43 48 73 95]
  2016 |  1 |  43 | [39 44 49 74 96]
 
period | id | age
  2016 |  0 |  38
  2016 |  1 |  43
  2016 |  2 |  48
  2016 |  3 |  73
  2016 |  4 |  95
```
