### ISSUE TITLE
periodic globals are not properly when in descending order 

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#236]
If I do import the following globals file
````
PERIOD,arrco_cotisation_taux_tranche_1
2010,0.075
2011,0.075
2012,0.075
2013,0.075
2014,0.07625
2015,0.0775
2016,0.0775
2017,0.0775
````
using this import section:
````yaml
globals:
    periodic:
        path: input/parametres.csv
        
        fields:
         - arrco_cotisation_taux_tranche_1: float
         - arrco_cotisation_taux_tranche_2: float
         - plafond_securite_sociale: int
         - arrco_valeur_point: float
         - arrco_salaire_de_reference: float
````
and declare them as follows:
````yaml
globals:
    periodic:
        fields:
         - arrco_cotisation_taux_tranche_1: float
         - arrco_cotisation_taux_tranche_2: float
         - plafond_securite_sociale: int
         - arrco_valeur_point: float
         - arrco_salaire_de_reference: float
````
everything is fine.

But if the globals are in decreasing PERIOD order 
````
PERIOD,arrco_cotisation_taux_tranche_1
2017,0.0775
2016,0.0775
2015,0.0775
2014,0.07625
2013,0.075
2012,0.075
2011,0.075
2010,0.075
````
the value of a the global `arrco_cotisation_taux_tranche_1` is `nan`.
Could you confirm that ?
If this is true it is quite annoying because it violates the principle of minimum surprise.
