### ISSUE TITLE
duration error if output file is unspecified

### ISSUE THREAD

**Issue by benjello** [liam2/liam2#300]
The `duration` function doesn't work when output file is not specified as in the following example:

```yaml
import: test_issue.yml.template


entities:
    person:
        fields:
            - age: {type: int, initialdata: True}

        processes:
            ageing():
                - age: age + 1

            test_issue():
                - test: duration(age > 20)

simulation:
    init:
        - person: [create]

    processes:
        - person: [ageing, test_issue]

    input:
        method: h5
        file: small.h5

    # output:
    #     file: simulation.h5

    logging:
        level: processes

    start_period: 2018
    periods: 3
```

Removing the comment marks of the output section solves the problem.
