### ISSUE TITLE
Somehow allow access to aggregate results from other functions

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#328]
In fact there is the same problem than #217 but between functions of the same entity. The "csv" workaround should work too (but that is sooo ugly). A global temporary works too (at least in 0.12) but throws a warning (they have been deprecated since 0.10 -- (https://liam2.plan.be/2015/06/15/version_0_10_released.html). In this case they are the lesser evil though.

```yaml
        processes:
            temp_array: 0

            compute_stuff():
                - temp_array: groupby(age, gender)

            use_array():
                - thing: temp_array / 10
```
