### ISSUE TITLE
implement coefficients_from context manager

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#329]
As a follow-up to #269 and the email discussion with BFP colleagues trying to generalize it to non-linear expressions, it might be a good idea to implement a context manager which takes variables from a file (or array/table) and makes them available as local variables:

```yaml
- with variables_from('thing.csv'):
    - thing1: c_age * age + c_age2 * age ** 2 + c_educ * education + c_constant
    - thing2: c_age * age + c_work * work + c_constant
```

and in thing.csv
```
__variable__,
      c_educ, c_age, c_age2, c_work, c_constant
       -0.02,   0.5,  -0.15,    0.2,       0.95
```

Or (more realistically):

```
__process__, __variable__,
           ,       c_educ, c_age, c_age2, c_work, c_constant
     thing1,        -0.02,   0.5,  -0.15,    0.0,       0.95
     thing2,          0.0,   0.4,    0.0,    0.2,        0.4
```

A couple thoughts about this: 
* this needs to share code with #131, as this issue does the same thing except it makes the loaded variables available temporarily
* this would not be specific to coefficients, but the example is. So the example above uses a c_ prefix for the coefficients related to each variable but this is just a convention.
* the `__process__` part is the most interesting (for coefficients) as it allows grouping several "coefficient" files in one to avoid a proliferation of them BUT it is also very fragile: it only works for processes which set a variable (no new() or other commands which do not need to store their data) and only works when there is a single process within the "with" block which sets that variable, so we probably need another way to distinguish each process, but I don't have any idea at the moment, except process order, which I don't really like. It would be great if we could manually give an "id" for a process, but I don't see a good way to do that. Maybe a specially formatted comment?

```yaml
- with variables_from('thing.csv'):
    # @thing1@
    - new('person', filter=c_age * age + c_age2 * age ** 2 + c_educ * education + c_constant > 0)
    # @thing2@
    - thing2: c_age * age + c_work * work + c_constant
```
or since this is only useful when we want to have different values for coefficients (I don't think there is a usecase for general variables) depending on the process, we can simply use different names and have some kind of convention:
```yaml
- with variables_from('thing.csv'):
    - new('person', filter=c_thing1_age * age + c_thing1_age2 * age ** 2 + c_thing1_educ * education + c_thing1_constant > 0)
    - thing2: c_thing2_age * age + c_thing2_work * work + c_thing2_constant
```
or use an (auto-indexed?) simple table:
```yaml
- thing: load('thing.csv')
- thing1: thing['thing1']
- thing2: thing['thing2']
- new('person', filter=thing1.c_age * age + thing1.c_age2 * age ** 2 + thing1.c_educ * education + thing1.c_constant > 0)
- thing2: thing2.c_age * age + thing2.c_work * work + thing2.c_constant
```
