### ISSUE TITLE
allow input fields to not be in the output

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#58]
It might be a good idea to rework the way to declare fields:
```yaml
input:
    - earny: float
    - wstatus: int
    - wzas: int
    - yob: int
output:
    - cscar: int
    - csw: float
    - cswl1: float
```
