### ISSUE TITLE
labeled enumerations

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#71]
eg workstate: 1: "unemployed, 2: "employee", 3: "civserv", ...
- display the labels in show/groupby instead of the numeric values
- use the labels in "read" expressions (instead of using macros)? Macros contain the == and can contain < or >, which is more generic, so I'm not sure it would be an improvement.
- use labels when setting new values (this could be done with macros, but that's not how they use it now), for example:

``` yaml
workstate: if(RETIREMENTAGE, 10, workstate)
# would become:
workstate: if(RETIREMENTAGE, RETIRED, workstate)

# More examples:
civilstate: {1: 'single', 2: 'married', 3: 'divored', 4: 'widow'}
civilstate: Enum(single=1, married=2, divorced=3, widow=4)

# this is shorter but is error-prone if we use external data for that
# field (which is usually the case)
civilstate: Enum('single', 'married', 'divored', 'widow')
ISSINGLE: civilstate.is('single')
ISSINGLE: civilstate == civilstate.single
```
