### ISSUE TITLE
make globals writeable

### ISSUE THREAD

**Issue by gdementen** [liam2/liam2#77]

**Comment by gdementen** [comment]
Here is what one can do to "modify" globals anyway. Either use a macro, or a separate/ preprocessing simulation with a dummy entity. Clearly not ideal but it's probably better than nothing...

```yaml
globals:
    periodic:
        path: param\globals.csv
        transposed: true
        fields:
            # PERIOD is implicit
            - VB: float
            - CPI: float
            - PRODLS: float

entities:
    dummy:
        fields:
            - vb: {type: float, initialdata: False}

        macros:
            LASTOBSPERIOD: 2014

            # only works if PRODLS is constant
            MACROVB: if(period <= 2014,
                        VB * 100 / CPI,
                        VB[2014] * 100 / CPI[2014] *
                            (1 + PRODLS[2014]) ** (period - 2014))

        processes:
            create:
                - new('dummy', number=1)
                - csv('id', 'fieldvb', 'MACROVB',
                      fname='constantpriceglobals.csv')

            compute_globals:
                - vb: if(period <= LASTOBSPERIOD,
                         VB * 100 / CPI,
                         vb * (1 + PRODLS))
                - csv(dump(vb, MACROVB, header=False),
                      fname='constantpriceglobals.csv', mode='a')

simulation:
    init:
        - dummy: [create]
    processes:
        - dummy: [compute_globals]

    input:
        method: void
        file: none

    output:
        file: simulation.h5

    start_period: 2002
    periods: 20
```
